apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/tls/ca.pem
    server: https://10.142.0.2
  name: local
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/tls/node.pem
    client-key: /etc/kubernetes/tls/node-key.pem
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context